print("Ayuda para el comando:")
print("La estructura del comando es: main.py (opcion -d ó -f) ruta (opción -b, -r, -t, -dt)")
print()
print("------------------------------------------------------------------------------------")
print("Descripción de las opciones:")
print("-h -> Muestra la ayuda del programa.")
print("-f -> Especifica el nombre del fichero que vamos a usar como datos de entrada.")
print("-d -> Especifica el directorio que contiene todos los ficheros a procesar.")
print("-b Muestra el beneficio de los items obtenidos.")
print("-r Muestra el peso sobrante en la mochila.")
print("-t Muestra el tiempo en segundos de la ejecución.")
print("-dt Muestra el identificador de los objetos elegidos.")
print("-----------------------------------------------------------------------------------")